services:
  - type: web
    name: dental-appointments
    env: python
    plan: free
    autoDeploy: true
    rootDir: app

    buildCommand: |
      poetry install --no-root --only main
      poetry run python manage.py collectstatic --noinput

    startCommand: |
      poetry run python manage.py migrate && poetry run python app/create_superuser.py && poetry run gunicorn config.wsgi:application --workers=2 --threads=4 --timeout=60 --preload

    healthCheckPath: /healthz/

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://your-service-name.onrender.com"
      - key: TIME_ZONE
        value: "America/Mexico_City"

      # —— Postgres ——
      - key: DB_ENGINE
        value: "postgres"
      - key: DB_SSL_REQUIRE
        value: "true"
      - key: POSTGRES_DB
        fromDatabase:
          name: dental-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: dental-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: dental-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: dental-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: dental-postgres
          property: port

databases:
  - name: dental-postgres
    plan: free